### ISSUE TITLE
Exception: Target class [hash] does not exist

### ISSUE THREAD

**Issue by malle-pietje** [saade/filament-laravel-log#27]
Hi,

Thanks for creating this plugin, I believe it's very useful!

One thing I discovered is when I add this callback for the `authorize()` method an Exception is thrown:
```php
        ->authorize(
            fn () => auth()->user()->hasRole('super_admin')
        ),
```
This is the Exception:
![image](https://github.com/saade/filament-laravel-log/assets/12016131/0d1630f4-6c5f-4276-a9a7-76f0d79b0e05)

Any clues on why this is happening?

**Comment by malle-pietje** [comment]
The install is using plain "stable" Filament with a couple of plugins enabled.

**Comment by malle-pietje** [comment]
For now I've solved the issue by creating a custom page that extends `Saade\FilamentLaravelLog\Pages\ViewLog` and uses the `HasPageShield` Trait provided by Shield like so:
```
<?php

namespace App\Filament\Pages;

use BezhanSalleh\FilamentShield\Traits\HasPageShield;
use Saade\FilamentLaravelLog\Pages\ViewLog;

class CustomLogs extends ViewLog
{
    use HasPageShield;

    public function getTitle(): string
    {
        return __('Application Logs');
    }
}

```
To hide the default, built-in, page the plugin is configured like so in the `PanelProvider`:
```
                FilamentLaravelLogPlugin::make()
                    ->navigationGroup('Logs')
                    ->navigationLabel('Application Logs')
                    ->navigationIcon('heroicon-o-bug-ant')
                    ->navigationSort(1)
                    ->slug('application_logs')
                    ->authorize(
                        fn () => false // hides the built-in page
                    ),
```

**Comment by Darker3x** [comment]
exactly same problem for me too

**Comment by Kwenziwa** [comment]
Im also facing the same issue.

**Comment by emjay64** [comment]
Same issue here as well.

**Comment by saade** [comment]
#38
