### ISSUE TITLE
logDirs([]) not working.

### ISSUE THREAD

**Issue by thedanmwangi** [saade/filament-laravel-log#29]
Hello, this is a very nice package.

However, I am unable to set custom log directories using the given method. It just falls back to the default "logs".

Has anyone else faced the same issue before?

![image](https://github.com/saade/filament-laravel-log/assets/66394054/badf197f-0928-4531-928e-920c9d0ddf55)

Basically, this is how I have implemented it. Each of the two directories has one log file. Neither is seen.

**Comment by saade** [comment]
Hey, see if v3.0.3 fixes your problem

**Comment by thedanmwangi** [comment]
It works perfectly. Love the response time also!
