### ISSUE TITLE
In authorization auth()->user() returns null

### ISSUE THREAD

**Issue by fcno** [saade/filament-laravel-log#32]
Maybe I'm missing something, but here goes.

According to the documentation, I could do something like this:

```php
FilamentLaravelLogPlugin::make()
  ->authorize(
      fn () => auth()->user()->isAdmin()
  )
```

However, the return from auth()->user() is always null. Apparently, in the life cycle, the providers are analyzed before the laravel framework retrieves the authenticated user's data.

Therefore, there is no way to do any checking there, since the user is not yet available.

Am I forgetting something or is there a bug here?

**Comment by saade** [comment]
There's a bug here, yes. I didnt have the time to look into an alternative yet.

**Comment by stuartcusackie** [comment]
Just in case anyone gets stuck....

The example doesn't work when using booleans from a database (0/1):
`->authorize(fn () => auth()->user()->is_super)`

So make sure to return an explicit bool:
`->authorize(fn(): bool => auth()->user()->is_super)`

**Comment by saade** [comment]
> The example doesn't work when using booleans from a database (0/1): `->authorize(fn () => auth()->user()->is_super)`

You need to cast your `is_super` to a boolean since database stores 0 / 1 for true / false. Add a `boolean` cast in your model's `$casts` for that property.
