### ISSUE TITLE
Publish config file command doesn't work

### ISSUE THREAD

**Issue by AlexMartinFR** [saade/filament-laravel-log#5]
Hello,

Thanks for your package, it's really neat!

There is an error in the readme regarding the publish file command though:

`php artisan vendor:publish --tag="filament-laravel-log-config"`

This returned the following error message:
_**No publishable resources for tag [filament-laravel-log-config].**_

The command to publish assets for me were the following:

- `php artisan vendor:publish --tag="log-config"`
- `php artisan vendor:publish --tag="log-translations"`
- `php artisan vendor:publish --tag="log-views"`

I had to look for the proper one by using the generic 'vendor:publish' command, as you can see below:

<img width="1000" alt="Capture d’écran 2022-06-02 à 10 56 53" src="https://user-images.githubusercontent.com/19224681/171594323-8baf9ea8-d9a9-494e-b876-798801000e24.png">

**Comment by saade** [comment]
thank you! I'll update the readme
